{
  "name": "your-project-name",
  "version": "1.0.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start -p $PORT -H 0.0.0.0"
  },
  "dependencies": {
    // other dependencies here, excluding 'serve' and 'react-scripts'
  },
  "devDependencies": {
    // other devDependencies here, excluding 'serve' and 'react-scripts'
  }
}